/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddClient.java
 *
 * Created on Jul 17, 2013, 2:38:44 PM
 */
package pos_project.UI;

import java.util.Locale;
import javax.swing.JOptionPane;
import pos_project.Action.ClientAction;
import pos_project.classes.Client;
import pos_project.classes.ErrorMessages;

/**
 *
 * @author Cif3r
 */
public class AddClientUi extends javax.swing.JDialog {
 private boolean editFlg = false;
 private boolean supplyFlg = false;
    private String clientNumber;
    /** Creates new form AddClient */
    public AddClientUi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public AddClientUi(java.awt.Frame parent, Boolean modal, boolean editflg, boolean supplyFlag) {
        supplyFlg = supplyFlag;
       initialize(parent, modal, editflg);
       if(supplyFlag){
           clientTypeComboBox.setSelectedIndex(1);
           creditLimitTextField.setEnabled(false);
       }
       clientTypeComboBox.setEnabled(false);
       
       
       
    }
    
    public AddClientUi(java.awt.Frame parent, Boolean modal, boolean editflg, String clientNumber) {
        initialize(parent, modal, editflg);
        Client c = Client.getClient(clientNumber);
        clientNumberTextField.setText(c.getClientNumber());
        clientNameTextField.setText(c.getClientName());
        clientAddressTextArea.setText(c.getClientAddress());
        clientPhoneTextField1.setText(c.getClientPhone());
        clientTypeComboBox.setSelectedIndex(c.getClientTypeFlag());
        creditLimitTextField.setText(c.getClientCreditLimit().toString());
        subTypeComboBox.setSelectedIndex(c.getClientSubType());
        this.clientNumber = clientNumber;
    }
    
    private void initialize(java.awt.Frame parent, boolean modal, boolean editflg){
        JOptionPane.setDefaultLocale(Locale.ENGLISH);
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        initComponents();
        creditLimitTextField.setText("5000.00");
        editFlg = editflg;
        if(editFlg){
            this.setTitle("Edit Client Details");
        } else {
            if(supplyFlg){
                this.setTitle("Add New Supplier");
            } else {
                this.setTitle("Add New Customer");
            }
        }
        for(Short i=0;i<Client.getClientSubTypeList().length;i++){
        subTypeComboBox.addItem(ClientAction.getSubtype(i));
       }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clientNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientAddressTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        creditLimitTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        AddClientOkButton = new javax.swing.JButton();
        AddClientCancelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        clientTypeComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        clientNumberTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        clientPhoneTextField1 = new javax.swing.JTextField();
        subTypeComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Client Details");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Client Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jLabel2, gridBagConstraints);

        clientNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNameTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(clientNameTextField, gridBagConstraints);

        jLabel3.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jLabel3, gridBagConstraints);

        clientAddressTextArea.setColumns(20);
        clientAddressTextArea.setRows(5);
        clientAddressTextArea.setPreferredSize(new java.awt.Dimension(204, 100));
        jScrollPane1.setViewportView(clientAddressTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel4.setText("Sub Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(creditLimitTextField, gridBagConstraints);

        AddClientOkButton.setText("OK");
        AddClientOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientOkButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddClientOkButton);

        AddClientCancelButton.setText("Cancel");
        AddClientCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientCancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddClientCancelButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel5.setText("Phone Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 5);
        getContentPane().add(jLabel5, gridBagConstraints);

        clientTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Customer", "Supplier" }));
        clientTypeComboBox.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(clientTypeComboBox, gridBagConstraints);

        jLabel6.setText("Client Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jLabel6, gridBagConstraints);

        clientNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNumberTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(clientNumberTextField, gridBagConstraints);

        jLabel7.setText("Credit Limit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        getContentPane().add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(clientPhoneTextField1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(subTypeComboBox, gridBagConstraints);

        jLabel8.setText("Client Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jLabel8, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNameTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_clientNameTextFieldActionPerformed

    private void AddClientOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientOkButtonActionPerformed
        // TODO add your handling code here:
        if(!checkClient(clientNameTextField.getText(), clientAddressTextArea.getText(),  clientPhoneTextField1.getText())){
            if(editFlg){
                int result = ClientAction.editClient(clientNameTextField.getText(), clientAddressTextArea.getText(),  clientPhoneTextField1.getText(), clientNumber, clientTypeComboBox.getSelectedIndex(), clientNumberTextField.getText(),creditLimitTextField.getText(),subTypeComboBox.getSelectedIndex());
                if(!(result < 0) ){
                    JOptionPane.showMessageDialog(this,ErrorMessages.CONFIRM_EDITED_CLIENT ,ErrorMessages.TITLE_SUCCESS,JOptionPane.INFORMATION_MESSAGE);
                }
                this.dispose();
                
            } else {
                int result = ClientAction.insertClient(clientNameTextField.getText(), clientAddressTextArea.getText(), clientPhoneTextField1.getText(), clientTypeComboBox.getSelectedIndex(),clientNumberTextField.getText(), creditLimitTextField.getText(),subTypeComboBox.getSelectedIndex());
                if(!(result < 0) ){
                    success();
                }
            }
        }
}//GEN-LAST:event_AddClientOkButtonActionPerformed

    private void AddClientCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientCancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_AddClientCancelButtonActionPerformed

    private void clientNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientNumberTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                AddClient dialog = new AddClient(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    
    private boolean checkClient(String name, String address, String phone){
        boolean errorFlg = false;
        String errMsg = new String();
        if(name.isEmpty()||name == null){
            errorFlg = true;
            errMsg += "* "+ErrorMessages.ERROR_CLIENT_NAME;
        }
        if(address.isEmpty()||address == null){
            errorFlg = true;
            errMsg += "* "+ErrorMessages.ERROR_CLIENT_ADDRESS;
        }
        if(phone.isEmpty()||phone == null){
            errorFlg = true;
            errMsg += "* "+ErrorMessages.ERROR_CLIENT_PHONE;
        }
        if(errorFlg){
            
            JOptionPane.showMessageDialog(this,errMsg ,ErrorMessages.TITLE_ERROR,JOptionPane.ERROR_MESSAGE);
        }
        
        return errorFlg;
        
        
    }
     
     private void success(){
          int answer = JOptionPane.showConfirmDialog(this,ErrorMessages.CONFIRM_ADDED_CLIENT,ErrorMessages.TITLE_SUCCESS,JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
          if(answer==0){
             clientNameTextField.requestFocus();
             clientNameTextField.setText("");
             clientAddressTextArea.setText("");
             creditLimitTextField.setText("");
          }else{
             this.dispose();
         }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClientCancelButton;
    private javax.swing.JButton AddClientOkButton;
    private javax.swing.JTextArea clientAddressTextArea;
    private javax.swing.JTextField clientNameTextField;
    private javax.swing.JTextField clientNumberTextField;
    private javax.swing.JTextField clientPhoneTextField1;
    private javax.swing.JComboBox clientTypeComboBox;
    private javax.swing.JTextField creditLimitTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox subTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
