/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddClient.java
 *
 * Created on Jul 17, 2013, 2:38:44 PM
 */
package pos_project.UI;

import java.util.Locale;
import javax.swing.JOptionPane;
import pos_project.Action.LocationAction;
import pos_project.classes.Client;
import pos_project.classes.ErrorMessages;

/**
 *
 * @author Cif3r
 */
public class AddLocationUi extends javax.swing.JDialog {
 private boolean editFlg = false;
 private boolean supplyFlg = false;
    private String clientNumber;
    /** Creates new form AddClient */
    public AddLocationUi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public AddLocationUi(java.awt.Frame parent, Boolean modal, boolean editflg, boolean supplyFlag) {
        supplyFlg = supplyFlag;
       initialize(parent, modal, editflg);
     
       
    }
    
    public AddLocationUi(java.awt.Frame parent, Boolean modal, boolean editflg, String clientNumber) {
        initialize(parent, modal, editflg);
        Client c = Client.getClient(clientNumber);
        locationNameTextField.setText(c.getClientName());
        locationAddressTextArea.setText(c.getClientAddress());
        locationPhoneTextField.setText(c.getClientPhone());
        this.clientNumber = clientNumber;
    }
    
    private void initialize(java.awt.Frame parent, boolean modal, boolean editflg){
        JOptionPane.setDefaultLocale(Locale.ENGLISH);
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        initComponents();
        editFlg = editflg;
        if(editFlg){
            this.setTitle("Edit Client Details");
        } else {
            if(supplyFlg){
                this.setTitle("Add New Supplier");
            } else {
                this.setTitle("Add New Customer");
            }
          
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        locationNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        locationAddressTextArea = new javax.swing.JTextArea();
        locationPhoneTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        AddClientOkButton = new javax.swing.JButton();
        AddClientCancelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Location Details");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Location Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jLabel2, gridBagConstraints);

        locationNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationNameTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        getContentPane().add(locationNameTextField, gridBagConstraints);

        jLabel3.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jLabel3, gridBagConstraints);

        locationAddressTextArea.setColumns(20);
        locationAddressTextArea.setRows(5);
        jScrollPane1.setViewportView(locationAddressTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 25);
        getContentPane().add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        getContentPane().add(locationPhoneTextField, gridBagConstraints);

        AddClientOkButton.setText("OK");
        AddClientOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientOkButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddClientOkButton);

        AddClientCancelButton.setText("Cancel");
        AddClientCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientCancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddClientCancelButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel5.setText("Phone Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jLabel5, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locationNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationNameTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_locationNameTextFieldActionPerformed

    private void AddClientOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientOkButtonActionPerformed
        // TODO add your handling code here:
        if(!checkClient(locationNameTextField.getText(), locationAddressTextArea.getText(), locationPhoneTextField.getText())){
            if(editFlg){
                int result = LocationAction.editLocation(locationNameTextField.getText(), locationAddressTextArea.getText(), locationPhoneTextField.getText(), clientNumber);
                if(!(result < 0) ){
                    JOptionPane.showMessageDialog(this,ErrorMessages.CONFIRM_EDITED_CLIENT ,ErrorMessages.TITLE_SUCCESS,JOptionPane.INFORMATION_MESSAGE);
                }
                this.dispose();
                
            } else {
                int result = LocationAction.insertLocation(locationNameTextField.getText(), locationAddressTextArea.getText(), locationPhoneTextField.getText());
                if(!(result < 0) ){
                    success();
                }
            }
        }
}//GEN-LAST:event_AddClientOkButtonActionPerformed

    private void AddClientCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientCancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_AddClientCancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                AddClient dialog = new AddClient(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    
    private boolean checkClient(String name, String address, String phone){
        boolean errorFlg = false;
        String errMsg = new String();
        if(name.isEmpty()||name == null){
            errorFlg = true;
            errMsg += "* "+ErrorMessages.ERROR_CLIENT_NAME;
        }
        if(address.isEmpty()||address == null){
            errorFlg = true;
            errMsg += "* "+ErrorMessages.ERROR_CLIENT_ADDRESS;
        }
        if(phone.isEmpty()||phone == null){
            errorFlg = true;
            errMsg += "* "+ErrorMessages.ERROR_CLIENT_PHONE;
        }
        if(errorFlg){
            
            JOptionPane.showMessageDialog(this,errMsg ,ErrorMessages.TITLE_ERROR,JOptionPane.ERROR_MESSAGE);
        }
        
        return errorFlg;
        
        
    }
     
     private void success(){
          int answer = JOptionPane.showConfirmDialog(this,ErrorMessages.CONFIRM_ADDED_LOCATION,ErrorMessages.TITLE_SUCCESS,JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
          if(answer==0){
             locationNameTextField.requestFocus();
             locationNameTextField.setText("");
             locationAddressTextArea.setText("");
             locationPhoneTextField.setText("");
          }else{
             this.dispose();
         }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClientCancelButton;
    private javax.swing.JButton AddClientOkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea locationAddressTextArea;
    private javax.swing.JTextField locationNameTextField;
    private javax.swing.JTextField locationPhoneTextField;
    // End of variables declaration//GEN-END:variables
}
