/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos_project.UI;

import java.awt.Color;
import java.awt.event.KeyListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import pos_project.Action.InvoiceAction;
import pos_project.classes.ErrorMessages;

/**
 *
 * @author Cifer
 */
public class InvoiceSearchUI2 extends javax.swing.JFrame {
TableRowSorter<DefaultTableModel> sorter;
    /**
     * Creates new form InvoiceSearchUI
     */
    public InvoiceSearchUI2() {
        initComponents();
    }
    
    public InvoiceSearchUI2(String itemNumber) {
        initComponents();
        initializeInvoiceTab(itemNumber);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Log Detail", "Date"
            }
        ));
        mainTable.setAutoscrolls(false);
        mainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(mainTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 709;
        gridBagConstraints.ipady = 213;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 15, 31, 15);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel1.setText("Search:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 10, 0);
        getContentPane().add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 0);
        getContentPane().add(txtSearch, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTableMouseReleased
        // TODO add your handling code here:
        InvoiceDetailsUi detailsPopUp = new InvoiceDetailsUi(new JFrame(),true, false, mainTable.getModel().getValueAt(mainTable.convertRowIndexToModel(mainTable.getSelectedRow()), 10).toString());

        detailsPopUp.setLocationRelativeTo(null);
        detailsPopUp.setVisible(true);
    }//GEN-LAST:event_mainTableMouseReleased

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InvoiceSearchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InvoiceSearchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InvoiceSearchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InvoiceSearchUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InvoiceSearchUI().setVisible(true);
//            }
//        });
//    }
    
     private void initializeInvoiceTab(String itemNumber){
        mainTable.getTableHeader().setReorderingAllowed(false);
        DefaultTableModel mod = InvoiceAction.searchInvoiceDataForMainTable(itemNumber);
        if(mod.getRowCount() > 0){
//         mod = ReturnAction.getMainTableData();
//         mod = PreorderAction.getMainTableData();
//         mod = InvoiceAction.getDebitMemoTableData();
        
              txtSearch.addKeyListener(new KeyListener(){
            public void keyReleased(java.awt.event.KeyEvent e){
                String text = txtSearch.getText();
                if (text.length() == 0) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text));
                }
            }

            public void keyPressed(java.awt.event.KeyEvent e){
            }

            public void keyTyped(java.awt.event.KeyEvent e){
                
            }

            });
        sorter = new TableRowSorter<DefaultTableModel>(mod);
//        mainTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int rows = mod.getRowCount();
        System.out.println("Row count = "+rows);
//        DefaultTableModel limitModel = new DefaultTableModel();
//        if(rows > 1000){
//            for(int i =1; i<10; i++){
//            limitModel.addRow((Vector) mod.getDataVector().elementAt(i));
//            }
//            mainTable.setModel(limitModel);
//        }
//        else{
//            mainTable.setModel(mod);
//        }
         mainTable.setModel(mod);
        mainTable.setRowSorter(sorter);
        mainTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        mainTable.setShowGrid(true);
        mainTable.setGridColor(Color.black);
//        mainTable.getColumnModel().removeColumn(mainTable.getColumnModel().getColumn(10));
        mainTable.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        }else{
            JOptionPane.showMessageDialog(this, ErrorMessages.ERROR_INVOICE_SEARCH, ErrorMessages.TITLE_ERROR, JOptionPane.WARNING_MESSAGE);
            this.dispose();
        }
    }
    
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
